buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.x.x") // Correct version
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.x.x") // Correct version
    }
}

plugins {
    id "com.android.application" // Or other plugins
    id "kotlin-android"        // Or other plugins
}

// ... rest of the build.gradle file ...